# nelmio_cors:
#   defaults:
#     allow_credentials: false
#     allow_origin: ["http://localhost:3000", "https://localhost:8000", http://localhost:7742]
#     allow_headers: ["Content-Type", "Authorization"]
#     allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
#     expose_headers: []
#     max_age: 3600
#     hosts: []
#     origin_regex: false
#     forced_allow_origin_value: ~
